kensakuKunn/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('searchKunn.urls'))
]

searchKunn/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('KensakuKunn', views.kensaku_kunn, name='KensakuKunn'),
    path('kekka/<int:blog_id>/', views.kekka, name='kekka'),
]

searchKunn/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    Title = models.CharField(max_length=100, verbose_name='タイトル')
    Author = models.CharField(max_length=50, verbose_name='著者')
    Category = models.CharField(max_length=50, verbose_name='カテゴリ')
    Registration_date = models.DateField(verbose_name='登録日')

    class Meta:
        verbose_name = '本'
        verbose_name_plural = '本'

    def __str__(self):
        return self.Title

searchKunn/views.py
from django.shortcuts import render
from django.contrib import messages
from django.db.models import Q
from django.views import generic
from functools import reduce
from operator import and_
from searchKunn.models import Book


# # Create your views here.
class IndexView(generic.ListView):
    model = Book
    template_name = 'searchKunn/index.html'

    """ オーバーライド """

    def get_queryset(self):
        queryset = Book.objects.order_by('-id')
        keyword = self.request.GET.get('keyword')

        if keyword:
            exclusion = set([' ', '　'])
            q_list = ''

            for i in keyword:
                if i in exclusion:
                    pass
                else:
                    q_list += i

            query = reduce(
                and_, [Q(Title__icontains=q) | Q(Author__icontains=q) | Q(Category__icontains=q) for q in q_list]
            )
            queryset = queryset.filter(query)
            messages.success(self.request, '「{}」の検索結果'.format(keyword))

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        keyword = self.request.GET.get('keyword')
        context["keyword"] = keyword
        context["count"] = self.get_queryset().count()
        return context


def kensaku_kunn(request):
    book = Book.objects.order_by('-id')
    return render(request, 'searchKunn/KensakuKunn.html', {
        'book_list': book,
    })


def kekka(request):
    return render(request, 'searchKunn/kekka.html', {
    })

searchKunn/templates/searchKunn/KensakuKunn.html
{% extends 'searchKunn/base.html' %}

{% block content %}
<div>
    <table class="table table-striped">
        <tr>
            <td>タイトル</td>
            <td>著者</td>
            <td>カテゴリー</td>
            <td>登録日</td>
        </tr>
        {% for book in book_list %}
        <tr>
            <td>{{ book.Title }}</td>
            <td>{{ book.Author }}</td>
            <td>{{ book.Category }}</td>
            <td>{{ book.Registration_date }}</td>

        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

searchKunn/templates/searchKunn/base.html
{% load static %}
{% load widget_tweaks %}
<html>
<head>
    <meta charset='utf-8'/>
    <title>うちの技術書検索くん</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">うちの技術書検索くん</a>
            </div>
        </nav>
    </header>
    <main>
        <form method="GET" action="{% url 'book:index' %}" class="table">
            <div class="input-group">
                <input type="search" class="form-control" name="keyword" type="text" placeholder="フリーワード">
                <button type="submit" class="btn btn-outline-success">検索</button>
            </div>
                <div class="text-end">
                  <a href="./KensakuKunn">すべてを表示する</a>
                </div>
        </form>
    </main>

    {% block content %}{% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

searchKunn/templates/searchKunn/index.html
{% extends 'searchKunn/base.html' %}


{% block content %}
<div>
    <div>"{{ keyword }}" を含む検索結果: {{ count }} 件</div>
    <table table class="table table-striped">
        <tr>
            <td>タイトル</td>
            <td>著者</td>
            <td>カテゴリー</td>
            <td>登録日</td>
        </tr>
        {% for book in book_list %}
        <tr>
            <td>{{ book.Title }}</td>
            <td>{{ book.Author }}</td>
            <td>{{ book.Category }}</td>
            <td>{{ book.Registration_date }}</td>

        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

searchKunn/templates/searchKunn/kekka.html
{% extends 'searchKunn/base.html' %}

{% block content %}

{% if is_paginated %}
    <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">前へ</span>
        </a>
        </li>

        <!-- 「前へ」と「次へ」の間の装飾文字 -->
        <li class="page-item">
        <span class="sr-only">..........</span>
        </li>
    {% endif %}

<!--
    {% for num in paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active">
            <span class="page-link">
            {{ num }}
            <span class="sr-only">(current)</span>
            </span>
            </li>
        {% else %}
            <li class="page-item">
            <a class="page-link" href="?page={{ num }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">{{ num }}</a>
            </li>
        {% endif %}
    {% endfor %}
-->

    {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}" pagearia-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">次へ</span>
        </a>
        </li>
    {% endif %}

    <li class="p-md-2">
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </li>
    </ul>
    </nav>
{% endif %}
{% endblock %}

searchKunn/templates/searchKunn/zenbu.html
{% extends 'searchKunn/base.html' %}

{% block content %}
<div>
    <table class="table table-striped">
        <tr>
            <td>タイトル</td>
            <td>著者</td>
            <td>カテゴリー</td>
            <td>登録日</td>
        </tr>
        {% for book in book_list %}
        <tr>
            <td>{{ book.Title }}</td>
            <td>{{ book.Author }}</td>
            <td>{{ book.Category }}</td>
            <td>{{ book.Registration_date }}</td>

        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}